# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-31 21:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('flight_number', models.IntegerField(blank=True, unique=True)),
                ('zone', models.CharField(blank=True, max_length=96, unique=True)),
                ('passengers', models.IntegerField(blank=True, unique=True)),
                ('flying_from', models.CharField(blank=True, max_length=96, unique=True)),
                ('flying_to', models.CharField(blank=True, max_length=96, unique=True)),
                ('terminal_number', models.IntegerField(blank=True, unique=True)),
                ('departure_date', models.DateField(blank=True, max_length=96, unique=True)),
                ('arrival_date', models.DateField(blank=True, max_length=96, unique=True)),
                ('status', models.CharField(blank=True, max_length=96, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pilot',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=96, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rank', models.CharField(blank=True, max_length=96, unique=True)),
                ('badge', models.CharField(blank=True, max_length=96, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TravelAgency',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(blank=True, max_length=96, unique=True)),
                ('flight_fares', models.CharField(blank=True, max_length=96, unique=True)),
                ('baggage_allowance', models.IntegerField(blank=True, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='pilot',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapi.Position'),
        ),
        migrations.AddField(
            model_name='flight',
            name='pilot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapi.Pilot'),
        ),
        migrations.AddField(
            model_name='flight',
            name='travelagency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flightapi.TravelAgency'),
        ),
    ]
